version: "3.9"

services:
  web:
    build:
      context: "sosu-frontend"
    container_name: sosu-web-container
    ports:
      - "8090:80"
  api:
    build:
      context: "SOSU2022_BackEnd/SOSU2022_BackEnd.WebApi"
    container_name: sosu-api-container-back
    ports:
      - "8091:80"